# Generated by Django 4.1.5 on 2023-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('u_phone', models.CharField(max_length=10)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_address', models.TextField(max_length=1000)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
