# Generated by Django 4.1.5 on 2023-08-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_bookingfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
