# Generated by Django 4.1.5 on 2023-08-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('u_phone', models.CharField(max_length=10)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_address', models.TextField(max_length=1000)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.account_type')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dic_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingField',
        ),
        migrations.AddField(
            model_name='booking',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branch'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
        ),
    ]
