# Generated by Django 4.1.5 on 2023-08-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_account_type_booking_branch_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('dic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branchname'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
