# Generated by Django 4.1.5 on 2023-08-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_branchname_alter_booking_branch_name_delete_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=255)),
                ('date_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
                ('u_phone', models.CharField(max_length=10)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_address', models.TextField(max_length=1000)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('ac_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.account_type')),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branchname')),
                ('dic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
