# Generated by Django 4.1.5 on 2023-08-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_bookings_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
