# Generated by Django 4.1.5 on 2023-08-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_bookings_date_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
