# Generated by Django 4.1.5 on 2023-08-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_rename_bookings_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_birth',
            field=models.DateField(),
        ),
    ]
